### ISSUE TITLE
java.lang.NoSuchFieldError: MATERIALS Crash

### ISSUE THREAD

**Issue by rckymtnrfc** [Leo40Git/ChainCraft#4]
I'm seeing the following crash when launching the game.

https://pastebin.com/Nsbk26LM

Thank you

**Comment by Leo40Git** [comment]
Another crash that I can't replicate in my development environment...
Fix coming out shortly.

**Comment by Leo40Git** [comment]
Should be fixed in 1.1.2.
Get it [here](https://github.com/Leo40Git/ChainCraft/releases/tag/v1.1.2), update will be up on Curse soon.

**Comment by rckymtnrfc** [comment]
Thank you!

**Comment by rckymtnrfc** [comment]
Sorry, now it's changed to the following crash.

java.lang.NoSuchFieldError: MISC

https://pastebin.com/PJqZWfqV

**Comment by Leo40Git** [comment]
No idea why this is happening. Might be an issue with the latest Forge version.

**Comment by Leo40Git** [comment]
Nevermind, I just screwed everything up. Version 1.1.3 will fix everything properly.

**Comment by Leo40Git** [comment]
ALL FIXED IN 1.1.3, FINALLY.
Grab it [here](https://github.com/Leo40Git/ChainCraft/releases/tag/v1.1.3), now being uploaded to Curse.
